---
apiVersion: v1
kind: Secret
metadata:
  name: rhug-angular-rhug-angular-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ultraJeffOrg/rhug-angular-frontend-gitops
